// This file is automatically generated.

namespace Steam4NET
{
    public enum ESteamFindFilter : int
    {
        eSteamFindLocalOnly = 0,
        eSteamFindRemoteOnly = 1,
        eSteamFindAll = 2,
    };
}