// This file is automatically generated.

namespace Steam4NET;

public enum ESteamSubscriptionBillingInfoType : int
{
    ePaymentCardInfo = 1,
    ePrepurchasedInfo = 2,
    eAccountBillingInfo = 3,
    eExternalBillingInfo = 4,
    ePaymentCardReceipt = 5,
    ePrepurchaseReceipt = 6,
    eEmptyReceipt = 7,
};