// This file is automatically generated.

namespace Steam4NET;

public enum ESteamPaymentCardType : int
{
    eVisa = 1,
    eMaster = 2,
    eAmericanExpress = 3,
    eDiscover = 4,
    eDinnersClub = 5,
    eJCB = 6,
};