// This file is automatically generated.

namespace Steam4NET;

public enum ESteamAppUpdateStatsQueryType : int
{
    ePhysicalBytesReceivedThisSession = 1,
    eAppReadyToLaunchStatus = 2,
    eAppPreloadStatus = 3,
    eAppEntireDepot = 4,
    eCacheBytesPresent = 5,
};