// This file is automatically generated.

namespace Steam4NET
{
    public enum AudioPlayback_Status : int
    {
        AudioPlayback_Undefined = 0,
        AudioPlayback_Playing = 1,
        AudioPlayback_Paused = 2,
        AudioPlayback_Idle = 3,
    };
}