// This file is automatically generated.
using System.Runtime.InteropServices;

namespace Steam4NET;

[StructLayout(LayoutKind.Sequential, Pack = 8)]
public struct TSteamSubscriptionBillingInfo
{
    public ESteamSubscriptionBillingInfoType eBillingInfoType;
};